name: C3 Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-latest
          #- ubuntu-24.04-arm
          - macos-14
          - macos-15
          - macos-latest
          - windows-2022
          - windows-latest
          - windows-11-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup C3
        if: runner.arch != 'ARM64' || runner.os != 'Windows'
        uses: jotrorox/setup-c3@v1

      - name: Setup C3 (Windows ARM64)
        if: runner.arch == 'ARM64' && runner.os == 'Windows'
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $zip = "$env:TEMP\c3.zip"
          Invoke-WebRequest -Uri "https://api.github.com/repos/c3lang/c3c/actions/artifacts/8081993070/zip" -OutFile $zip -Headers @{Authorization = "Bearer $env:GH_TOKEN"}
          Expand-Archive -Path $zip -DestinationPath "$HOME\c3" -Force
          "$HOME\c3" >> $env:GITHUB_PATH

      - name: Build
        run: |
          c3c build

      - name: Run
        run: |
          c3c run